config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks", confirmations: "confirmations", sessions: "sessions" }, :path => "account"

  devise_scope :user do
    # Alias routes for sign in, up, and out
    get 'signin', to: redirect('account/sign_in')
    get 'sign_in', to: redirect('account/sign_in')
    get 'login', to: redirect('account/sign_in')
    get 'signup', to: redirect('account/sign_up')
    get 'sign_up', to: redirect('account/sign_up')
    get 'register', to: redirect('account/sign_up')
    get 'signout', to: redirect('account/sign_out')
    get 'sign_out', to: redirect('account/sign_out')
    get 'logout', to: redirect('account/sign_out')
    get 'account/sign_out', to: 'devise/sessions#destroy'
      # Fixes bug where users with JS disabled couldn't log out, without
      # needing to create a form to post to the sessions#destroy method.
    # Terms of Service/EULA
    match 'policy/tos' => 'registrations#accept_tos', via: [:get, :post]

    # Account information & settings
    get 'account', to: redirect('account/overview')
    get 'account/overview' => 'registrations#account_overview'
    #match 'account/common' => 'registrations#edit', via: [:get, :patch, :post] # normal settings (name, email, password, SSO, etc)
    get 'account/settings' => 'registrations#edit'
    get 'account/settings(.:id)' => 'registrations#edit', to: redirect('accounts/settings'), as: :user
      # Without this second route for accounts/settings, if the user leaves
      # password blank but types something in for confirm_password, returning
      # false from RegistrationsController.update_resources throws a
      # NoMethodError "undefined method 'user_url'". The second route fixes it.

    # Account security - managing TOTP & U2F 2FA
    match 'account/security' => 'registrations#account_security_settings', via: [:get, :post]
    match 'account/security/2fa/recovery_codes', to: 'registrations#account_recovery_codes', via: [:get]
    match 'account/security/2fa/totp', to: 'registrations#account_manage_totp', via: [:get, :post]
    match 'account/security/2fa/totp/regen', to: 'registrations#account_regen_totp', via: [:post]
    match 'account/security/2fa/totp/u2f', to: 'registrations#account_manage_totp_with_u2f', via: [:get, :post]
    scope 'account/security/2fa/u2f', as: 'account_security_2fa_u2f' do
      match 'keys', to: 'credentials#index', via: [:get]
      match 'add', to: 'credentials#create', via: [:get, :post]
      match ':token_id/edit', to: 'credentials#edit', via: [:get, :post], as: 'edit'
      match ':token_id/delete/totp', to: 'credentials#delete_with_totp', via: [:get, :post], as: 'delete_with_totp'
      match ':token_id/delete/u2f', to: 'credentials#delete_with_u2f', via: [:get, :post], as: 'delete_with_u2f'
    end
    # Authenticating with TOTP & U2F 2FA
    match 'account/auth/2fa/totp', to: 'sessions#two_factor_auth_totp', via: [:get, :post]
    scope 'account/auth/2fa/u2f', as: 'account_auth_2fa_u2f' do
      match 'prompt', to: 'sessions#two_factor_auth_webauthn', via: [:get, :post]
    end
    # Account SSO
    match 'account/sign_up/sso' => 'registrations#finish_sso', via: [:get, :post, :delete], :as => :finish_sso
    delete 'account/auth(/:provider)', to: 'omniauth_callbacks#destroy' # for removing SSO integrations from an account

    # Omniauth provider setup
    match '/account/auth/:provider/setup' => 'sessions#setup_omniauth', via: [:get]
  end

  # Account preferences (not managed by Devise)
  match 'account/ui(/:user)' => 'preferences#account_display_settings', via: [:get, :put], :as => :account_ui
  match 'account/notifications' => 'preferences#account_notification_settings', via: [:get, :post, :put]

  # Reports
  resources :reports, except: [:edit, :resolve], :path => 'account/reports'
  match 'account/reports/:id/edit', to: 'reports#edit', via: [:get, :post, :patch], :as => :edit_report
  match 'account/reports/:id/resolve', to: 'reports#resolve', via: [:get, :post, :patch], :as => :resolve_report

  # Admin console
  namespace :admin do
    get '', to: 'dashboard#index'
    get 'reports', to: 'dashboard#reports'
    get 'searches', to: 'dashboard#searches'
    get 'syslog', to: 'dashboard#system_log'
    get 'sysprefs', to: 'dashboard#system_settings'
    get 'users', to: 'dashboard#user_management'
    match 'users/(:id)', to: 'dashboard#user_profile', via: [:get, :post, :delete], as: :manage_user
    resources :eulas, only: [:new, :create, :index, :show], :path => 'tos'
    # The reason I use "resources" above is because with "resource", the :index route does not get created
    # But for bans, if I did "resources", that causes problems when trying to create new bans for some reason
    # TODO: figure out why that happens and try to make it use "resources" like eulas above
    resource :bans, only: [:new, :create, :index], :path => 'users/:user/bans', as: :user_ban
    resource :bans, only: [:show, :update, :delete], :path => 'users/:user/bans/:id', as: :user_ban
    resources :conversations, only: [:index, :show, :new, :create, :destroy], :path => 'messages' do
      resources :messages, only: [:new, :create, :edit, :destroy, :update], :path => 'replies'
      match 'replies/:id/hide', to: 'messages#hide', via: [:post], as: :hide
      match 'replies/:id/mark_unread', to: 'messages#mark_unread', via: [:post], as: :mark_unread
      match 'lock', to: 'conversations#lock', via: [:get], as: :lock
    end
  end

  # User messages
  resources :conversations, only: [:index, :show, :new, :create, :destroy], :path => 'account/messages' do
    resources :messages, only: [:new, :create, :edit, :destroy, :update], :path => 'replies'
    match 'replies/:id/hide', to: 'messages#hide', via: [:post], as: :hide
    match 'replies/:id/mark_unread', to: 'messages#mark_unread', via: [:post], as: :mark_unread
  end

  # Chat logs
  chat_log_route_exceptions = []
  unless Rails.configuration.application[:chat_logs][:allow_creation]
    chat_log_route_exceptions = [:new, :create]
  end
  resources :chat_logs, except: chat_log_route_exceptions do
    collection do
      get 'advanced_search', to: 'chat_logs#advanced_search'
      post 'advanced_search', to: 'chat_logs#advanced_search'
    end
  end

  # Static pages
  get 'help', to: 'pages#help_index'
  get 'help/markdown', to: 'pages#help_markdown'
  get 'help/regex', to: 'pages#help_regex'

  root to: 'pages#index'

end

app/controllers/admin/eulas_controller.rb
class Admin::EulasController < ApplicationController
  include Admin::DashboardHelper
  include Admin::EulasHelper
  before_action :authenticate_user!
  before_action :admin_tab_badge_data
  before_action :set_tab_data
  before_action :set_eula, only: [:show]
  before_action :verify_permissions
  after_action :clear_flashes, except: [:create]

  def index
    @prefs = ApplicationHelper.common_prefs

    # Search fields
    search_params = search_eula_params

    # Extract params
    eula_note = search_params[:note] if search_params[:note] && search_params[:note].length > 0
    eula_eula_text = search_params[:eula_text] if search_params[:eula_text] && search_params[:eula_text].length > 0
    eula_publisher = search_params[:publisher] if search_params[:publisher] && search_params[:publisher].length > 0
    eula_start_time = search_params[:start_time] if search_params[:start_time] && search_params[:start_time].length > 0
    eula_end_time = search_params[:end_time] if search_params[:end_time] && search_params[:end_time].length > 0
    eula_per_page = search_params[:per_page] if search_params[:per_page] && search_params[:per_page].length > 0

    @search_errors = Eula.validate_search(note: eula_note, eula_text: eula_eula_text, publisher: eula_publisher,
                                          start_time: eula_start_time, end_time: eula_end_time, per_page: eula_per_page)

    query_notes = {}
    if @search_errors.none?
      begin
        query_time = Benchmark.realtime {
          @eulas = Eula.search(note: eula_note, eula_text: eula_eula_text, publisher: eula_publisher,
                               start_time: eula_start_time, end_time: eula_end_time)
        }
        @eulas.count # see ConversationsController for why I need this
      rescue RegexpError, ActiveRecord::StatementInvalid => err
        if !@search_errors.any? { |error| error.include? 'regex' }
          # Only add error message if invalid regex messages not yet added to list
          if err.message.match(ApplicationHelper.pg_invalid_regex_locator)
            @search_errors["#{I18n.t('.activerecord.errors.models.eula.attributes.default.regex_error_generic')} "] =
                            "(#{I18n.t('.activerecord.errors.models.eula.attributes.default.regex_error_details_known')}: " \
                            "#{err.message.match(ApplicationHelper.pg_invalid_regex_locator)[1]})"
          else
            @search_errors["#{I18n.t('.activerecord.errors.models.eula.attributes.default.regex_error_generic')} "] =
                            "(#{I18n.t('.activerecord.errors.models.eula.attributes.default.regex_error_details_unknown')})"
            logger.warn("Admin EULAs controller - failed to match rescued regex error message")
            logger.debug("Regex error message: #{err.message}, class: #{err.message.class}")
          end
        end
        query_time = Benchmark.realtime {
          @eulas = Eula.all
        }
      end
    else
      flash[:error] = I18n.t('.activerecord.errors.generic.search.failed')
      query_notes = flash.to_h.merge(:search_errors => @search_errors)
      eula_per_page = nil
      # If there is a search error, I reset per page, as it is used in the calls to
      # @eulas.order, meaning if this is not reset, invalid per page might be used.
      # This is not needed for the other form fields because none of those will be
      # used in the event of a search error being reported, but per_page still is,
      # hence the nullification.
      query_time = Benchmark.realtime {
        @eulas = Eula.all
      }
    end

    custom_per_page = per_page == params[:per_page]
    # TODO: create Search record here

    @eulas = @eulas.order("#{dash_eula_sort_column} #{sort_direction}").page(params[:page]).per(eula_per_page)
  end

  def show
  end

  def new
    @eula ||= Eula.new
  end

  def create
    @eula = Eula.new(eula_params)
    @eula.user_id = current_user.id
    @eula.publisher = current_user.id
    respond_to do |format|
      if @eula.save
        # Prevent current user from getting logged out
        user = current_user
        user.eula_accepted_at = Time.now()
        user.save
        eula_acceptance_notice = 'To prevent you from being logged out, your account has automatically been updated to accept the TOS'
        flash[:success] = 'TOS published'
        flash[:notice] = eula_acceptance_notice
        format.html { redirect_to admin_eula_path(@eula.id) }
        format.json { render :show, status: :created, location: @eula }
      else
        format.html { render :new }
        format.json { render json: @eula.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def eula_params
    params.require(:eula).permit(
      :note,
      :eula_text
    )
  end

  def search_eula_params
    params.permit(
      :utf8,
      :note,
      :eula_text,
      :publisher,
      :start_time,
      :end_time,
      :per_page,
      :column,
      :direction
    )
  end

  def set_tab_data
    @eulas_tab = true
  end

  def set_eula
    @eula = Eula.find(params[:id])
  end

  def permissions_list
    {
      :index => [:admin],
      :new => [:admin],
      :show => [:admin],
      :create => [:admin]
    }
  end

  def verify_permissions
    if permissions_list[action_name.to_sym]&.index(current_user.role.to_sym).nil?
      # action_name is a Rails method for the controller method name
      # ( https://stackoverflow.com/a/4274222 )
      # Safe navigation operator (&) only calls if not nil.
      flash[:error] = I18n.t('.activerecord.errors.permissions.general.unauthorized')
      redirect_to root_path
    end
  end
end

app/helpers/admin/eulas_helper.rb
module Admin::EulasHelper
  include ApplicationHelper

  # Sorting

  def dash_eula_search_sort_link(column, title = nil)
    # The title parameter is used if the column name isn't what I want to use
    title ||= column.titleize
    direction = column == dash_eula_sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "fas fa-caret-up" : "fas fa-caret-down"
    icon = column == dash_eula_sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, params.permit(:column, :direction, :note, :eula_text, :publisher, :start_time, :end_time, :page, :highlight, :per_page, :utf8).merge(:column => column, :direction => direction)
  end

  def dash_eula_sortable_columns
    ["id", "created_at", "publisher"]
  end

  def dash_eula_sort_column
    user_column = Current.user.user_preference.default_sort_col
    if user_column == "sender"
      user_column = "publisher"
      # I use publisher instead of user_id because user_id is nullified on deletion
    else # "date" or "channel"
      user_column = "created_at"
    end
    dash_eula_sortable_columns.include?(params[:column]) ? params[:column] : user_column
    # Only uses user preferences default column sort when user has
    # not clicked on any other columns
  end
end

app/views/admin/eulas/_form.html.erb
<%= form_with(model: @eula, url: admin_eulas_path, local: true) do |form| %>
  <% if !eula.nil? && eula.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(eula.errors.count, "error") %> prohibited this TOS from being saved:</h4>

      <ul>
        <% eula.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :note, :for => :eula_note %>
    <%= form.text_field :note, :id => :eula_note, :class => "form-control", :rows => "1" %>
    <small id="eula_noteHelp" class="form-text text-muted">A note as to why this TOS is being published (i.e. fixing mistakes); maximum <%= Eula.max_note_length %> characters. Not visible to regular users.</small>
  </div>

  <div class="field form-group">
    <%= form.label :eula_text, "User Agreement", :for => :eula_text %>
    <%= form.text_area :eula_text, :id => :eula_text, :class => "form-control", :rows => "12" %>
    <small id="eula_textHelp" class="form-text text-muted">You can use <%= link_to "Markdown", help_markdown_path%> in this field. Inlined HTML will be ignored; maximum <%= number_with_delimiter(Eula.max_eula_length, :delimiter => ',') %> characters.</small>
    <%# I use number_with_delimiter because this number is (most likely) going to be very large. I found out about it from https://stackoverflow.com/a/1078366 %>
  </div>

  <div class="actions">
    <%= form.submit "Publish", :class => "btn btn-primary", :role => "button" %>
  </div>
<% end %>

app/views/admin/eulas/_search_form.html.erb
<div class="form-inline justify-content-center">
  <%= form_tag(admin_eulas_path, method: :get) do %>
    <div class="row mb-3">
      <div class="col col-12 col-md-6">
        <%= label_tag :note, "Note", :for => :note, :class => "mb-2" %>
        <div class="field form-group">
          <%= text_field_tag :note, params[:note], :class => "form-control col-md-12" %>
          <small id="noteHelp" class="form-text text-muted">Case insensitive search; to use regex, view the <%= link_to "regex documentation", help_regex_path %></small>
        </div>
      </div>
      <div class="col col-12 col-md-6">
        <%= label_tag :eula_text, "Agreement Text", :for => :eula_text, :class => "mb-2" %>
        <div class="field form-group">
          <%= text_field_tag :eula_text, params[:eula_text], :class => "form-control col-md-12" %>
          <small id="eula_textHelp" class="form-text text-muted">Case insensitive search; to use regex, view the <%= link_to "regex documentation", help_regex_path %></small>
        </div>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col col-12 col-md-3">
        <%= label_tag :publisher, "Publishing User ID", :for => :publisher, :class => "mb-2" %>
        <div class="field form-group">
          <%= text_field_tag :publisher, params[:publisher], :class => "form-control col-md-12" %>
          <small id="publisherHelp" class="form-text text-muted">A user's ID or primary email address</small>
        </div>
      </div>
      <div class="col col-12 col-md-3">
        <%= label_tag :start_time, "Date Published Start", :for => :start_time, :class => "card-text mb-2" %>
        <div class="field form-group">
          <div class="row">
            <div class="col">
              <div class="form-group">
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                  <%= text_field_tag :start_time, params[:start_time], :class => "form-control datetimepicker-input col-md-12", data: { target: "#datetimepicker1" }, :rows => "1" %>
                  <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker" title="Interactive date/time selector">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>
            </div>
            <script type="text/javascript">
                $(function () {
                    $('#datetimepicker1').datetimepicker({
                        format: '<%= "#{@prefs[:js_dt_format]}" %>'
                        <%#= Documentation: https://tempusdominus.github.io/bootstrap-4/Options/#format %>
                    });
                });
            </script>
          </div>
          <small id="start_timeHelp" class="form-text text-muted">Lower inclusive boundary.<br />Format: <%= @prefs[:user_dt_format] %></small>
        </div>
      </div>
      <div class="col col-12 col-md-3">
        <%= label_tag :end_time, "Date Published End", :for => :end_time, :class => "card-text mb-2" %>
        <div class="field form-group">
          <div class="row">
            <div class="col">
              <div class="form-group">
                <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                  <%= text_field_tag :end_time, params[:end_time], :class => "form-control datetimepicker-input col-md-12", data: { target: "#datetimepicker2" }, :rows => "1" %>
                  <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker" title="Interactive date/time selector">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>
            </div>
            <script type="text/javascript">
                $(function () {
                    $('#datetimepicker2').datetimepicker({
                        format: '<%= "#{@prefs[:js_dt_format]}" %>'
                        <%#= Documentation: https://tempusdominus.github.io/bootstrap-4/Options/#format %>
                    });
                });
            </script>
          </div>
          <small id="end_timeHelp" class="form-text text-muted">Upper inclusive boundary.<br />Format: <%= @prefs[:user_dt_format] %></small>
          <noscript>
            <small id="end_timeHelp" class="form-text text-muted">You have JavaScript disabled, the date picker will not work without it.</small>
          </noscript>
        </div>
      </div>
      <div class="col col-md-3">
        <%= label_tag :per_page, "Results per Page", :for => :per_page, :class => "mb-2" %>
        <div class="field form-group">
          <%= number_field_tag :per_page, params[:per_page], :min => PreferencesHelper.min_per_page, :max => PreferencesHelper.max_per_page, :class => "form-control col-md-12" %>
          <small id="per_pageHelp" class="form-text text-muted">Enter as a number from <%= PreferencesHelper.min_per_page %> to <%= PreferencesHelper.max_per_page %>. Default: <%= @prefs[:per_page] %></small>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col">
        <div class="actions">
          <%= link_to "Publish New TOS", new_admin_eula_path, class: "btn btn-secondary" %>
          <%= submit_tag 'Search', :class => "btn btn-primary col-auto float-right", :name => nil %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/eulas/edit.html.erb
<h1>Editing Eula</h1>

<%= render 'form', eula: @eula %>

<%= link_to 'Show', @eula %> |
<%= link_to 'Back', eulas_path %>

app/views/admin/eulas/index.html.erb
<%= render "admin/shared/admin_title" %>

<div class="row">
  <div class="col">
    <%= render "admin/shared/admin_tabs" %>
    <div class="card border-top-0">
      <div class="card-body">
        <%- if !@search_errors.nil? && @search_errors.any? %>
          <div id="error_explanation">
            <h4><%= pluralize(@search_errors.count, "error") %> prohibited your search from being executed:</h4>
            <ul>
              <% @search_errors.each do |attr, message| %>
                <li><%= "#{attr} #{message}" %></li>
              <% end %>
            </ul>
            <p class="card-text">A blank search has been executed.</p>
          </div>
          <hr />
        <% end -%>
        <h4 class="card-title">Terms of Services</h4>
        <%= render 'admin/eulas/search_form' %>

        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th scope="col"><%= dash_eula_search_sort_link("id", "ID") %></th>
                <th scope="col"><%= dash_eula_search_sort_link("created_at", "Date Published") %></th>
                <th scope="col"><%= dash_eula_search_sort_link("publisher", "Publisher") %></th>
                <th scope="col">Note</th>
                <th scope="col">Text</th>
              </tr>
            </thead>
            <tbody>
              <% if @eulas.count == 0 %>
                <td colspan="5">No Terms of Services found</td>
              <% else %>
                <% @eulas.each do |eula| %>
                  <tr>
                    <td><%= eula.id %></td>
                    <td><%= ApplicationHelper.datetime_to_str(eula.created_at, show_offset: false, show_seconds: true) %></td>
                    <td>
                      <% if eula.user_id? %>
                        <%= link_to "#{eula.user.name} (ID #{eula.user_id})", admin_manage_user_path(eula.user_id) %>
                      <% elsif eula.publisher == Rails.configuration.application[:common][:system_user_id] %>
                        <%= "ID #{eula.publisher} (System)" %>
                      <% else %>
                        <%= "ID #{eula.publisher} (Deleted)" %>
                      <% end %>
                    </td>
                    <td><%= eula.note %></td>
                    <td><%= link_to 'View', admin_eula_path(eula) %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="pagination justify-content-center">
          <%= paginate @eulas, theme: 'bootstrap4' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/eulas/new.html.erb
<%= render "admin/shared/admin_title" %>

<div class="row">
  <div class="col">
    <%= render "admin/shared/admin_tabs" %>
    <div class="card border-top-0">
      <div class="card-body">
        <h4 class="card-title">New Terms of Service</h4>
        <div class="row">
          <div class="col">
            <%= render 'form', eula: @eula %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/eulas/show.html.erb
<%= render "admin/shared/admin_title" %>

<div class="row">
  <div class="col">
    <%= render "admin/shared/admin_tabs" %>
    <div class="card border-top-0">
      <div class="card-body">
        <h4 class="card-title">Terms of Service <%= @eula.id %> Details</h4>

        <p class="card-text mb-0">
          Date Published:
          <%= ApplicationHelper.datetime_to_str(@eula.created_at, show_offset: false, show_seconds: true) %>
        </p>

        <p class="card-text mb-0">
          Published by:
          <% if @eula.user_id? %>
            <%= link_to "#{@eula.user.name} (ID #{@eula.user_id})", admin_manage_user_path(@eula.user_id) %>
          <% elsif @eula.publisher == Rails.configuration.application[:common][:system_user_id] %>
            <%= "ID #{@eula.publisher} (System)" %>
          <% else %>
            <%= "ID #{@eula.publisher} (Deleted)" %>
          <% end %>
        </p>

        <p class="card-text">
          <% if @eula.is_latest? %>
            <i>
              This is the currently active user agreement.
            </i>
          <% else %>
            <i>
              This is <b>not</b> the currently active user agreement.
              It has been succeeded by <a href="<%= admin_eula_path(Eula.get_latest_eula.id) %>">#<%= Eula.get_latest_eula.id %></a>.
            </i>
          <% end %>
        </p>

        <div class="card">
          <div class="card-header">
            <span>Note: <%= @eula.note %></span>
          </div>
          <div class="card-body">
            <%= markdown(@eula.eula_text) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>