config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks", confirmations: "confirmations", sessions: "sessions" }, :path => "account"

  devise_scope :user do
    # Alias routes for sign in, up, and out
    get 'signin', to: redirect('account/sign_in')
    get 'sign_in', to: redirect('account/sign_in')
    get 'login', to: redirect('account/sign_in')
    get 'signup', to: redirect('account/sign_up')
    get 'sign_up', to: redirect('account/sign_up')
    get 'register', to: redirect('account/sign_up')
    get 'signout', to: redirect('account/sign_out')
    get 'sign_out', to: redirect('account/sign_out')
    get 'logout', to: redirect('account/sign_out')
    get 'account/sign_out', to: 'devise/sessions#destroy'
      # Fixes bug where users with JS disabled couldn't log out, without
      # needing to create a form to post to the sessions#destroy method.
    # Terms of Service/EULA
    match 'policy/tos' => 'registrations#accept_tos', via: [:get, :post]

    # Account information & settings
    get 'account', to: redirect('account/overview')
    get 'account/overview' => 'registrations#account_overview'
    #match 'account/common' => 'registrations#edit', via: [:get, :patch, :post] # normal settings (name, email, password, SSO, etc)
    get 'account/settings' => 'registrations#edit'
    get 'account/settings(.:id)' => 'registrations#edit', to: redirect('accounts/settings'), as: :user
      # Without this second route for accounts/settings, if the user leaves
      # password blank but types something in for confirm_password, returning
      # false from RegistrationsController.update_resources throws a
      # NoMethodError "undefined method 'user_url'". The second route fixes it.

    # Account security - managing TOTP & U2F 2FA
    match 'account/security' => 'registrations#account_security_settings', via: [:get, :post]
    match 'account/security/2fa/recovery_codes', to: 'registrations#account_recovery_codes', via: [:get]
    match 'account/security/2fa/totp', to: 'registrations#account_manage_totp', via: [:get, :post]
    match 'account/security/2fa/totp/regen', to: 'registrations#account_regen_totp', via: [:post]
    match 'account/security/2fa/totp/u2f', to: 'registrations#account_manage_totp_with_u2f', via: [:get, :post]
    scope 'account/security/2fa/u2f', as: 'account_security_2fa_u2f' do
      match 'keys', to: 'credentials#index', via: [:get]
      match 'add', to: 'credentials#create', via: [:get, :post]
      match ':token_id/edit', to: 'credentials#edit', via: [:get, :post], as: 'edit'
      match ':token_id/delete/totp', to: 'credentials#delete_with_totp', via: [:get, :post], as: 'delete_with_totp'
      match ':token_id/delete/u2f', to: 'credentials#delete_with_u2f', via: [:get, :post], as: 'delete_with_u2f'
    end
    # Authenticating with TOTP & U2F 2FA
    match 'account/auth/2fa/totp', to: 'sessions#two_factor_auth_totp', via: [:get, :post]
    scope 'account/auth/2fa/u2f', as: 'account_auth_2fa_u2f' do
      match 'prompt', to: 'sessions#two_factor_auth_webauthn', via: [:get, :post]
    end
    # Account SSO
    match 'account/sign_up/sso' => 'registrations#finish_sso', via: [:get, :post, :delete], :as => :finish_sso
    delete 'account/auth(/:provider)', to: 'omniauth_callbacks#destroy' # for removing SSO integrations from an account

    # Omniauth provider setup
    match '/account/auth/:provider/setup' => 'sessions#setup_omniauth', via: [:get]
  end

  # Account preferences (not managed by Devise)
  match 'account/ui(/:user)' => 'preferences#account_display_settings', via: [:get, :put], :as => :account_ui
  match 'account/notifications' => 'preferences#account_notification_settings', via: [:get, :post, :put]

  # Reports
  resources :reports, except: [:edit, :resolve], :path => 'account/reports'
  match 'account/reports/:id/edit', to: 'reports#edit', via: [:get, :post, :patch], :as => :edit_report
  match 'account/reports/:id/resolve', to: 'reports#resolve', via: [:get, :post, :patch], :as => :resolve_report

  # Admin console
  namespace :admin do
    get '', to: 'dashboard#index'
    get 'reports', to: 'dashboard#reports'
    get 'searches', to: 'dashboard#searches'
    get 'syslog', to: 'dashboard#system_log'
    get 'sysprefs', to: 'dashboard#system_settings'
    get 'users', to: 'dashboard#user_management'
    match 'users/(:id)', to: 'dashboard#user_profile', via: [:get, :post, :delete], as: :manage_user
    resources :eulas, only: [:new, :create, :index, :show], :path => 'tos'
    # The reason I use "resources" above is because with "resource", the :index route does not get created
    # But for bans, if I did "resources", that causes problems when trying to create new bans for some reason
    # TODO: figure out why that happens and try to make it use "resources" like eulas above
    resource :bans, only: [:new, :create, :index], :path => 'users/:user/bans', as: :user_ban
    resource :bans, only: [:show, :update, :delete], :path => 'users/:user/bans/:id', as: :user_ban
    resources :conversations, only: [:index, :show, :new, :create, :destroy], :path => 'messages' do
      resources :messages, only: [:new, :create, :edit, :destroy, :update], :path => 'replies'
      match 'replies/:id/hide', to: 'messages#hide', via: [:post], as: :hide
      match 'replies/:id/mark_unread', to: 'messages#mark_unread', via: [:post], as: :mark_unread
      match 'lock', to: 'conversations#lock', via: [:get], as: :lock
    end
  end

  # User messages
  resources :conversations, only: [:index, :show, :new, :create, :destroy], :path => 'account/messages' do
    resources :messages, only: [:new, :create, :edit, :destroy, :update], :path => 'replies'
    match 'replies/:id/hide', to: 'messages#hide', via: [:post], as: :hide
    match 'replies/:id/mark_unread', to: 'messages#mark_unread', via: [:post], as: :mark_unread
  end

  # Chat logs
  chat_log_route_exceptions = []
  unless Rails.configuration.application[:chat_logs][:allow_creation]
    chat_log_route_exceptions = [:new, :create]
  end
  resources :chat_logs, except: chat_log_route_exceptions do
    collection do
      get 'advanced_search', to: 'chat_logs#advanced_search'
      post 'advanced_search', to: 'chat_logs#advanced_search'
    end
  end

  # Static pages
  get 'help', to: 'pages#help_index'
  get 'help/markdown', to: 'pages#help_markdown'
  get 'help/regex', to: 'pages#help_regex'

  root to: 'pages#index'

end

app/helpers/chat_logs_helper.rb
module ChatLogsHelper
  include ApplicationHelper

  # Sorting
  def chatlog_sort_link(column, title = nil)
    # The title parameter is used if the column name isn't what I want to use
    title ||= column.titleize
    direction = column == chatlog_sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "fas fa-caret-up" : "fas fa-caret-down"
    icon = column == chatlog_sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, params.permit(:column, :direction, :channel, :sender, :query, :advanced_query, :case_sensitive, :base_id, :start_id, :end_id, :base_time, :start_time, :end_time, :valid_search, :page, :utf8, :highlight, :per_page).merge(:column => column, :direction => direction)
  end

  def chatlog_sortable_columns
    ["channel", "sender", "date"]
  end

  def chatlog_sort_column
    user_column = Current.user.user_preference.default_sort_col
    chatlog_sortable_columns.include?(params[:column]) ? params[:column] : user_column
      # Only uses user preferences default column sort when user has
      # not clicked on any other columns
  end

  # Validations
  def self.chatlog_channel_regex
    if Rails.configuration.application[:chat_logs][:channel][:require_prefix]
      /^[#&][a-z0-9_]{#{Rails.configuration.application[:chat_logs][:channel][:min_length]},#{Rails.configuration.application[:chat_logs][:channel][:max_length]}}$/
    else
      /^[#&]?[a-z0-9_]{#{Rails.configuration.application[:chat_logs][:channel][:min_length]},#{Rails.configuration.application[:chat_logs][:channel][:max_length]}}$/
    end
  end

  def chatlog_channel_regex
    ChatLogsHelper.chatlog_channel_regex
  end

  def self.chatlog_channel_regex_description
    # This has 2 paths depending on the configuration, hence this method rather
    # than just calling the I18n string from each instance it is needed in the
    # code.
    min_length = Rails.configuration.application[:chat_logs][:channel][:min_length]
    max_length = Rails.configuration.application[:chat_logs][:channel][:max_length]
    if Rails.configuration.application[:chat_logs][:channel][:require_prefix]
      #"must start with a # or & and contain #{Rails.configuration.application[:chat_logs][:channel][:min_length]}-#{Rails.configuration.application[:chat_logs][:channel][:max_length]} lowercase letters, numbers, or underscores"
      I18n.t('.activerecord.errors.models.chat_log.attributes.channel.invalid_require_prefix',
             min: min_length, max: max_length)
    else
      #"may start with a # or & and must contain #{Rails.configuration.application[:chat_logs][:channel][:min_length]}-#{Rails.configuration.application[:chat_logs][:channel][:max_length]} lowercase letters, numbers, or underscores"
      I18n.t('.activerecord.errors.models.chat_log.attributes.channel.invalid_optional_prefix',
             min: min_length, max: max_length)
    end
  end

  def chatlog_channel_regex_description
    ChatLogsHelper.chatlog_channel_regex_description
  end

  def self.chatlog_sender_regex
    /^[a-z0-9_]{#{Rails.configuration.application[:chat_logs][:sender][:min_length]},#{Rails.configuration.application[:chat_logs][:sender][:max_length]}}$/
  end

  def chatlog_sender_regex
    ChatLogsHelper.chatlog_sender_regex
  end

  def self.chatlog_sender_regex_description
    min_length = Rails.configuration.application[:chat_logs][:sender][:min_length]
    max_length = Rails.configuration.application[:chat_logs][:sender][:max_length]
    #"must contain #{Rails.configuration.application[:chat_logs][:sender][:min_length]}-#{Rails.configuration.application[:chat_logs][:sender][:max_length]} lowercase letters, numbers, or underscores"
    I18n.t('.activerecord.errors.models.chat_log.attributes.sender.invalid',
           min: min_length, max: max_length)
  end
  
  def chatlog_sender_regex_description
    ChatLogsHelper.chatlog_sender_regex_description
  end
  
  def self.chatlog_max_id
    if User.type_for_attribute('id') == :bigint
      2**63-1
    else
      2**31-1
    end
  end
  
  def chatlog_max_id
    ChatLogsHelper.chatlog_max_id
  end

  def self.chatlog_edit_path_regex
    # Used to make sure a URL is for editing a ChatLog in the _form view, as
    # the delete button is only shown for existing ChatLogs, and you cannot
    # call "current_page?(controller: 'chat_logs', action: 'edit')" from the
    # create view, as it will throw an error (since a non-existent ChatLog
    # cannot have an edit view).
    # This will match "chat_logs/123" in "/chat_logs/123/edit". I did not try
    # to match "/edit" in the URL, as a validation error will cause a redirect
    # with _form rendering on "/chat_logs/123". This ensures the first and n-th
    # attempts at editing a ChatLog will still display the delete button.
    /chat_logs\/\d+/
  end
end

app/views/chat_logs/_advanced_search_form.html.erb
<%= form_with(model: chat_log, local: true) do |form| %>
  <% if !chat_log.nil? && chat_log.errors.any? %>
    <hr />
    <div id="error_explanation">
      <h4><%= pluralize(chat_log.errors.count, "error") %> prohibited this search from executing:</h4>
      <ul>
      <% chat_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%- if !@errors.nil? && @errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@errors.count, "error") %> prohibited your search from being executed:</h4>
      <ul>
        <% @errors.each do |attr, message| %>
          <li><%= "#{attr} #{message}" %></li>
        <% end %>
      </ul>
    </div>
    <hr />
  <% end -%>

  <h5>Search tips:</h5>
  <ul>
    <li>You do not have to fill in all fields, but it is recommended you narrow your search terms to get more relevant results.</li>
    <li>You can use regular expressions in the Message field if you surround your query with forward slashes, like this:
    <div class="card">
      <div class="card-body">
      <pre class="code-block">/^(tim(Clip|Dinero|Guest420|Minus|Oh|Plus)(\s)*){3,}$/</pre>
      </div>
    </div>
    To learn more about regular expressions and how to escape forward slashes to avoid searching with them, view the <%= link_to "regex documentation", help_regex_path %>.
    </li>
    <li>The message field does a partial match if you are not using regular expressions, all other fields look for exact matches.</li>
    <li>Time selection uses UTC<%= @prefs[:tz_offset] %> and uses the format "<%= @prefs[:user_dt_format] %>" (to modify the date format, change 12/24 hour time, or set your timezone, go to the Appearance & Localization settings menu).</li>
    <li>Searching by message IDs can be unintuitive, as some older messages may have been added after logging began, so you may find some messages you did not expect. This is not a bug.</li>
    <li>To change the default number of search results per page (affects both basic and advanced searches, and viewing logs without searching anything), go to the Appearance & Localization settings menu.</li>
  </ul>
  <hr />
  <div class="field form-group">
    <%= form.label :channel, "Channel", :for => :chat_log_channel %>
    <%= form.text_field :channel, id: :chat_log_channel, :class => "form-control", :rows => "1" %>
    <small id="channelHelp" class="form-text text-muted"><%= ChatLogsHelper.chatlog_channel_regex_description.upcase_first %></small>
    <%# upcase_first just capitalizes the first character https://api.rubyonrails.org/classes/String.html#method-i-upcase_first %>
  </div>

  <div class="field form-group">
    <%= form.label :sender, "Sender", :for => :chat_log_sender %>
    <%= form.text_field :sender, id: :chat_log_sender, :class => "form-control", :rows => "1" %>
    <small id="senderHelp" class="form-text text-muted"><%= ChatLogsHelper.chatlog_sender_regex_description.upcase_first %></small>
    <%# upcase_first just capitalizes the first character https://api.rubyonrails.org/classes/String.html#method-i-upcase_first %>
  </div>

  <div class="field form-group">
    <%= form.label :message, "Message", :for => :chat_log_message %>
    <%= form.text_area :message, id: :chat_log_message, :class => "form-control" %>

    <%= form.check_box :case_sensitive, id: :case_sensitive_checkbox, :class => "field form-group form-check-input" %>
    <%= form.label :case_sensitive, "Search case sensitive?", :for => :case_sensitive_checkbox %> (When used with regular expressions, the entire query is executed as sensitive/insensitive.)
  </div>

  <div class="form-row">
    <div class="field form-group col">
      <%= form.label :start_time, "Starting Time", :for => :chat_log_date %>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
              <%= form.text_field :start_time, id: :chat_log_start_time, :class => "form-control datetimepicker-input", data: { target: "#datetimepicker1" }, :rows => "1" %>
              <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker" title="Interactive date/time selector">
                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
              </div>
            </div>
          </div>
        </div>
        <script type="text/javascript">
        $(function () {
          $('#datetimepicker1').datetimepicker({
            format: '<%= "#{@prefs[:js_dt_format]}" %>'
            <%#= Documentation: https://tempusdominus.github.io/bootstrap-4/Options/#format %>
          });
        });
        </script>
      </div>
      <small id="start_timeHelp" class="form-text text-muted">Format: <%= @prefs[:user_dt_format] %></small>
      <noscript>
        <small id="start_timeHelp" class="form-text text-muted">You have JavaScript disabled, the date picker will not work without it.</small>
      </noscript>
    </div>

    <div class="field form-group col">
      <%= form.label :end_time, "Ending Time", :for => :chat_log_date %>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
              <%= form.text_field :end_time, id: :chat_log_end_time, :class => "form-control datetimepicker-input", data: { target: "#datetimepicker2" }, :rows => "1" %>
              <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker" title="Interactive date/time selector">
                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
              </div>
            </div>
          </div>
        </div>
        <script type="text/javascript">
        $(function () {
          $('#datetimepicker2').datetimepicker({
            format: '<%= "#{@prefs[:js_dt_format]}" %>'
            <%#= Documentation: https://tempusdominus.github.io/bootstrap-4/Options/#format %>
          });
        });
        </script>
      </div>
      <small id="end_timeHelp" class="form-text text-muted">Format: <%= @prefs[:user_dt_format] %></small>
      <noscript>
        <small id="end_timeHelp" class="form-text text-muted">You have JavaScript disabled, the date picker will not work without it.</small>
      </noscript>
    </div>
  </div>
  <div class="form-row">
    <div class="field form-group col">
      <%= form.label :start_id, "Starting ID", :for => :start_id %>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <%= form.number_field :start_id, id: :start_id, :min => "1", :max => ChatLogsHelper.chatlog_max_id, :class => "form-control" %>
            <small id="start_idHelp" class="form-text text-muted">Lower inclusive boundary</small>
          </div>
        </div>
      </div>
    </div>

    <div class="field form-group col">
      <%= form.label :end_id, "Ending ID", :for => :end_id %>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <%= form.number_field :end_id, id: :end_id, :min => "1", :max => ChatLogsHelper.chatlog_max_id, :class => "form-control" %>
            <small id="end_idHelp" class="form-text text-muted">Upper inclusive boundary</small>
          </div>
        </div>
      </div>
    </div>

    <div class="field form-group col">
      <%= form.label :per_page, "Results per Page", :for => :per_page %>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <%= form.number_field :per_page, id: :per_page, :min => PreferencesHelper.min_per_page, :max => PreferencesHelper.max_per_page, :class => "form-control" %>
            <small id="per_pageHelp" class="form-text text-muted">Enter as a number from <%= PreferencesHelper.min_per_page %> to <%= PreferencesHelper.max_per_page %>. Default: <%= @prefs[:per_page] %>.</small>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Search", :class => "btn btn-primary", :role => "button", :checked => "checked" %>
  </div>

<% end %>

app/views/chat_logs/_chat_logs_title.html.erb
<h2>Chat Logs</h2>
<div style="height: 1.0em;"><br></div>

app/views/chat_logs/advanced_search.html.erb
<h2>Advanced Search</h2>
<div style="height: 1.0em;"><br></div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <%= render 'advanced_search_form', chat_log: @advanced_search %>
      </div>
    </div>
  </div>
</div>
<br>
<%= link_to 'Back to Message List', chat_logs_path %>

app/views/chat_logs/edit.html.erb
<h2>Editing Chat Log</h2>
<div style="height: 1.0em;"><br></div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <%= render 'form', chat_log: @chat_log %>
      </div>
    </div>
  </div>
</div>

<br />
<%= link_to 'View Message (Discard Changes)', @chat_log, data: { confirm: 'Are you sure you want to discard your changes?' } %>
| <%= link_to 'Back to Message List', chat_logs_path %>

app/views/chat_logs/index.html.erb
<%= render 'chat_logs/chat_logs_title' %>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <div class="form-inline justify-content-center">
          <%= form_tag(chat_logs_path, method: :get) do %>
            <%= text_field_tag :query, params[:query], placeholder: "Search messages", :class => "form-control col-sm-6", autofocus: true %>
            <%= submit_tag 'Search', :class => "btn btn-primary ml-2 my-sm-2 col-auto", :name => nil %>
            <%= link_to 'Advanced Search', advanced_search_chat_logs_path, :class => "btn btn-secondary ml-2 my-sm-2 col-auto" %>
          <% end %>
        </div>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col" class="borderless-top"><%= chatlog_sort_link "channel" %></th>
                <th scope="col" class="borderless-top"><%= chatlog_sort_link "sender" %></th>
                <th scope="col" class="borderless-top">Message</th>
                <th scope="col" class="borderless-top"><%= chatlog_sort_link "date", "Time (UTC#{@UserTZOffset})" %></th>
                <th scope="col" class="borderless-top"></th>
              </tr>
            </thead>
            <tbody>
              <%- if @chat_logs.count == 0 %>
                <tr>
                  <td colspan="5">No results found</td>
                </tr>
              <% else %>
                <% @chat_logs.each do |chat_log| %>
                  <tr class="<%= 'table-primary' if !params[:highlight].nil? && chat_log.id == params[:highlight].to_i =%>">
                    <td><%= chat_log.channel %></td>
                    <td><%= chat_log.sender %></td>
                    <td class="message-list"><%= chat_log.message %></td>
                    <td><%= ApplicationHelper.datetime_to_str(ApplicationHelper.datetime_from_epoch(chat_log.date), show_offset: false, show_seconds: true) %></td>
                    <td><%= link_to 'Show', chat_log %></td>
                  </tr>
                <% end %>
              <% end -%>
            </tbody>
          </table>
        </div>
        <div class="pagination justify-content-center">
          <%= paginate @chat_logs, theme: 'bootstrap4' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chat_logs/new.html.erb
<h1>New Chat Log</h1>

<%= render 'form', chat_log: @chat_log %>

<%= link_to 'Back', chat_logs_path %>

app/views/chat_logs/show.html.erb
<h2>Message Details</h2>
<div style="height: 1.0em;">
  <br />
</div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <!-- No table header because I can't disable the bold text -->
            <tbody>
              <tr>
                <td class="border-top-0 pt-0">Channel</td>
                <%# Removed "col-sm-1" because of a pretty big rendering bug in Chrome when using the Dark theme %>
                <%# border-top-0 eliminates the top border, pt-0 reduces the gap between the top row and the card-body top border %>
                <td class="border-top-0 pt-0"><%= @chat_log.channel %></td>
              </tr>
              <tr>
                <td>Sender</td>
                <td><%= @chat_log.sender %></td>
              </tr>
              <tr>
                <td>Message</td>
                <td><%= @chat_log.message %></td>
              </tr>
              <tr>
                <td>Date/Time</td>
                <td><%= ApplicationHelper.datetime_to_str(ApplicationHelper.datetime_from_epoch(@chat_log.date), show_offset: true, show_seconds: true) %></td>
              </tr>
              <% if @chat_log.chat_log_edits.count > 0 %>
                <% last_cle = @chat_log.chat_log_edits.last %>
                <tr>
                  <td>Edited?</td>
                  <td>Yes - <%= ApplicationHelper.datetime_to_str(last_cle.created_at, show_offset: true, show_seconds: true) %></td>
                </tr>
                <tr>
                  <td>Edit Reason</td>
                  <td><%= last_cle.external_justification %></td>
                </tr>
              <% else %>
                <tr>
                  <td>Edited?</td>
                  <td>No</td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <p class="card-text">You can change the date format and timezone used in your account settings.</p>
        <div>
          <%= link_to 'Context', chat_logs_path(:channel => @chat_log.channel, :base_id => @chat_log.id, :highlight => @chat_log.id), :class => "btn btn-secondary" %>

          <%- if UserHelper.permissions_list[:edit].index(current_user.role.to_sym) %>
            <%= link_to 'Edit/Delete Message', edit_chat_log_path(@chat_log), :class => "btn btn-danger float-right" %>
          <% end -%>
          <%= link_to 'Report Message', new_report_path(:msg_id => @chat_log.id), :class => "btn btn-warning float-right" %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if current_user.role == 'admin' %>
<br />
<h2>Message Edits</h2>
<div style="height: 1.0em;">
  <br />
</div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr class="table-borderless">
                <th scope="col">Editor</th>
                <th scope="col">Internal Justification</th>
                <th scope="col">External Justification</th>
                <th scope="col">Edited On</th>
              </tr>
            </thead>
            <tbody>
              <% if @chat_log.chat_log_edits.count == 0 %>
                <td colspan="4">This message has never been edited.</td>
              <% else %>
                <% @chat_log.chat_log_edits.each do |cle| %>
                  <tr>
                    <td>
                      <% if cle.editor %>
                        <%= link_to cle.editor.name, admin_manage_user_path(cle.editor) %>
                      <% else %>
                        Deleted User (ID <%= cle.edited_by %>)
                      <% end %>
                    </td>
                    <td><%= cle.internal_justification %></td>
                    <td><%= cle.external_justification %></td>
                    <td><%= ApplicationHelper.datetime_to_str(cle.created_at, show_offset: true, show_seconds: true) %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<br />

<%= link_to 'Back to Results', session[:return_to] %>
| <%= link_to 'New Search', chat_logs_path %>