config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks", confirmations: "confirmations", sessions: "sessions" }, :path => "account"

  devise_scope :user do
    # Alias routes for sign in, up, and out
    get 'signin', to: redirect('account/sign_in')
    get 'sign_in', to: redirect('account/sign_in')
    get 'login', to: redirect('account/sign_in')
    get 'signup', to: redirect('account/sign_up')
    get 'sign_up', to: redirect('account/sign_up')
    get 'register', to: redirect('account/sign_up')
    get 'signout', to: redirect('account/sign_out')
    get 'sign_out', to: redirect('account/sign_out')
    get 'logout', to: redirect('account/sign_out')
    get 'account/sign_out', to: 'devise/sessions#destroy'
      # Fixes bug where users with JS disabled couldn't log out, without
      # needing to create a form to post to the sessions#destroy method.
    # Terms of Service/EULA
    match 'policy/tos' => 'registrations#accept_tos', via: [:get, :post]

    # Account information & settings
    get 'account', to: redirect('account/overview')
    get 'account/overview' => 'registrations#account_overview'
    #match 'account/common' => 'registrations#edit', via: [:get, :patch, :post] # normal settings (name, email, password, SSO, etc)
    get 'account/settings' => 'registrations#edit'
    get 'account/settings(.:id)' => 'registrations#edit', to: redirect('accounts/settings'), as: :user
      # Without this second route for accounts/settings, if the user leaves
      # password blank but types something in for confirm_password, returning
      # false from RegistrationsController.update_resources throws a
      # NoMethodError "undefined method 'user_url'". The second route fixes it.

    # Account security - managing TOTP & U2F 2FA
    match 'account/security' => 'registrations#account_security_settings', via: [:get, :post]
    match 'account/security/2fa/recovery_codes', to: 'registrations#account_recovery_codes', via: [:get]
    match 'account/security/2fa/totp', to: 'registrations#account_manage_totp', via: [:get, :post]
    match 'account/security/2fa/totp/regen', to: 'registrations#account_regen_totp', via: [:post]
    match 'account/security/2fa/totp/u2f', to: 'registrations#account_manage_totp_with_u2f', via: [:get, :post]
    scope 'account/security/2fa/u2f', as: 'account_security_2fa_u2f' do
      match 'keys', to: 'credentials#index', via: [:get]
      match 'add', to: 'credentials#create', via: [:get, :post]
      match ':token_id/edit', to: 'credentials#edit', via: [:get, :post], as: 'edit'
      match ':token_id/delete/totp', to: 'credentials#delete_with_totp', via: [:get, :post], as: 'delete_with_totp'
      match ':token_id/delete/u2f', to: 'credentials#delete_with_u2f', via: [:get, :post], as: 'delete_with_u2f'
    end
    # Authenticating with TOTP & U2F 2FA
    match 'account/auth/2fa/totp', to: 'sessions#two_factor_auth_totp', via: [:get, :post]
    scope 'account/auth/2fa/u2f', as: 'account_auth_2fa_u2f' do
      match 'prompt', to: 'sessions#two_factor_auth_webauthn', via: [:get, :post]
    end
    # Account SSO
    match 'account/sign_up/sso' => 'registrations#finish_sso', via: [:get, :post, :delete], :as => :finish_sso
    delete 'account/auth(/:provider)', to: 'omniauth_callbacks#destroy' # for removing SSO integrations from an account

    # Omniauth provider setup
    match '/account/auth/:provider/setup' => 'sessions#setup_omniauth', via: [:get]
  end

  # Account preferences (not managed by Devise)
  match 'account/ui(/:user)' => 'preferences#account_display_settings', via: [:get, :put], :as => :account_ui
  match 'account/notifications' => 'preferences#account_notification_settings', via: [:get, :post, :put]

  # Reports
  resources :reports, except: [:edit, :resolve], :path => 'account/reports'
  match 'account/reports/:id/edit', to: 'reports#edit', via: [:get, :post, :patch], :as => :edit_report
  match 'account/reports/:id/resolve', to: 'reports#resolve', via: [:get, :post, :patch], :as => :resolve_report

  # Admin console
  namespace :admin do
    get '', to: 'dashboard#index'
    get 'reports', to: 'dashboard#reports'
    get 'searches', to: 'dashboard#searches'
    get 'syslog', to: 'dashboard#system_log'
    get 'sysprefs', to: 'dashboard#system_settings'
    get 'users', to: 'dashboard#user_management'
    match 'users/(:id)', to: 'dashboard#user_profile', via: [:get, :post, :delete], as: :manage_user
    resources :eulas, only: [:new, :create, :index, :show], :path => 'tos'
    # The reason I use "resources" above is because with "resource", the :index route does not get created
    # But for bans, if I did "resources", that causes problems when trying to create new bans for some reason
    # TODO: figure out why that happens and try to make it use "resources" like eulas above
    resource :bans, only: [:new, :create, :index], :path => 'users/:user/bans', as: :user_ban
    resource :bans, only: [:show, :update, :delete], :path => 'users/:user/bans/:id', as: :user_ban
    resources :conversations, only: [:index, :show, :new, :create, :destroy], :path => 'messages' do
      resources :messages, only: [:new, :create, :edit, :destroy, :update], :path => 'replies'
      match 'replies/:id/hide', to: 'messages#hide', via: [:post], as: :hide
      match 'replies/:id/mark_unread', to: 'messages#mark_unread', via: [:post], as: :mark_unread
      match 'lock', to: 'conversations#lock', via: [:get], as: :lock
    end
  end

  # User messages
  resources :conversations, only: [:index, :show, :new, :create, :destroy], :path => 'account/messages' do
    resources :messages, only: [:new, :create, :edit, :destroy, :update], :path => 'replies'
    match 'replies/:id/hide', to: 'messages#hide', via: [:post], as: :hide
    match 'replies/:id/mark_unread', to: 'messages#mark_unread', via: [:post], as: :mark_unread
  end

  # Chat logs
  chat_log_route_exceptions = []
  unless Rails.configuration.application[:chat_logs][:allow_creation]
    chat_log_route_exceptions = [:new, :create]
  end
  resources :chat_logs, except: chat_log_route_exceptions do
    collection do
      get 'advanced_search', to: 'chat_logs#advanced_search'
      post 'advanced_search', to: 'chat_logs#advanced_search'
    end
  end

  # Static pages
  get 'help', to: 'pages#help_index'
  get 'help/markdown', to: 'pages#help_markdown'
  get 'help/regex', to: 'pages#help_regex'

  root to: 'pages#index'

end

app/helpers/reports_helper.rb
module ReportsHelper
  include ApplicationHelper

  def self.report_statuses
    {
      'All': 'all',
      'Resolved': 'resolved',
      'Unresolved': 'unresolved'
    }
  end

  # Sorting
  def report_sort_link(column, title = nil)
    # The title parameter is used if the column name isn't what I want to use
    title ||= column.titleize
    direction = column == report_sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "fas fa-caret-up" : "fas fa-caret-down"
    icon = column == report_sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, params.permit(:column, :direction, :id, :channel, :sender, :advanced_query, :resolved_at, :resolved, :reason, :start_time, :end_time, :msg_id, :user_id, :resolver_id, :valid_search, :page, :highlight, :per_page, :utf8).merge(:column => column, :direction => direction)
  end

  def report_sortable_columns
    ["id", "msg_channel", "msg_id", "msg_sender", "created_at", "resolved"]
  end

  def report_sort_column
    user_column = Current.user.user_preference.default_sort_col
    user_column = "created_at" if user_column == "date"
    user_column = "msg_sender" if user_column == "sender"
    user_column = "msg_channel" if user_column == "channel"
    report_sortable_columns.include?(params[:column]) ? params[:column] : user_column
      # Only uses user preferences default column sort when user has
      # not clicked on any other columns
  end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <hr />
    <div id="error_explanation">
      <h4><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h4>
      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group hide">
    <%= form.label :msg_id, for: :msg_id %>
    <%= form.number_field :msg_id, id: :msg_id, :min => "1", :value => params[:msg_id], :readonly => true, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <div class="mb-2">
      <%= form.label :report_reason, :class => "mb-0" %><span> (maximum <%= Rails.configuration.application[:common][:string_type_max_length] %> characters):</span>
    </div>
    <%= form.text_field :report_reason, :id => "report_reason", :class => "form-control" %>
    <small id="report_reasonHelp" class="form-text text-muted">Potential reporting reasons include personal information (address, phone number, etc.), highly objectional links, illegal content, etc.</small>
    <small id="report_reasonHelp" class="form-text text-muted">Abusing the reports system may result in your account being banned.</small>
  </div>

  <div class="actions">
    <%= form.submit "Submit Report", :class => "btn btn-primary" %>
    <%= link_to "View Your Reports", reports_path, :class => "btn btn-secondary" %>
  </div>
<% end %>

app/views/reports/_msg_edit_form.html.erb
<%= form_with(model: report, local: true, url: edit_report_path(@report)) do |form| %>
  <% if report.errors.any? %>
    <hr />
    <div id="error_explanation">
      <h4><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h4>
      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <div class="mb-2">
      <%= form.label :msg_text, "New Message", :class => "mb-0" %>
    </div>
    <%= form.text_field :msg_text, :class => "form-control" %>
    <small id="report_reasonHelp" class="form-text text-muted">Replace edited elements with [redacted], e.g. "My SSN is 123-45-6789." → "My SSN is [redacted]".</small>
  </div>

  <div class="actions">
    <%= form.submit "Edit", :class => "btn btn-warning" %>
    <%= link_to "Back", report_path(@report), :class => "btn btn-secondary" %>
  </div>
<% end %>

app/views/reports/_resolve_form.html.erb
<%= form_with(model: @report, url: resolve_report_path, method: :patch, local: true) do |form| %>
  <% if @report.errors.any? %>
    <hr />
    <div id="error_explanation">
      <h4><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h4>
      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group hide">
    <%= form.label :msg_id, for: :msg_id %>
    <%= form.number_field :msg_id, id: :msg_id, :min => "1", :value => params[:msg_id], :readonly => true, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <div class="mb-2">
      <%= form.label :resolving_action, "Action taken", for: :resolving_action, :class => "mb-0" %><span> (maximum <%= Rails.configuration.application[:common][:string_type_max_length] %> characters):</span>
    </div>
    <%= form.text_field :resolving_action, id: :resolving_action, :class => "form-control" %>
    <small id="resolving_actionHelp" class="form-text text-muted">The action taken will be visible to the user who reported the message.</small>
  </div>

  <div class="actions">
    <%- if !@report.resolved? %>
      <%= form.submit "Mark as Resolved", :class => "btn btn-primary" %>
    <% else %>
      <%= form.submit "Update Action Taken", :class => "btn btn-primary" %>
    <% end -%>
  </div>
<% end %>

app/views/reports/_search_form.html.erb
<div class="form-inline justify-content-center">
  <%= form_tag(reports_path, method: :get) do %>
    <div class="row mb-2">
      <div class="col col-12 col-md-2">
        <%= label_tag :resolved, "Status", :for => :resolved, :class => "card-text mb-2" %>
        <div class="field form-group mb-3">
          <%= select_tag :resolved, options_for_select(ReportsHelper.report_statuses, params[:resolved]), :class => "form-control col-md-12" %>
          <small id="resolvedHelp" class="form-text text-muted">Resolved status of a report</small>
        </div>
      </div>
      <div class="col col-12 col-md-4">
        <%= label_tag :reason, "Reporting Reason", :for => :reason, :class => "card-text mb-2" %>
        <div class="field form-group">
          <%= text_field_tag :reason, params[:reason], :class => "form-control col-md-12" %>
          <small id="reasonHelp" class="form-text text-muted">Case insensitive search; to use regex, view the <%= link_to "regex documentation", help_regex_path %></small>
        </div>
      </div>
      <div class="col col-12 col-md-4">
        <%= label_tag :advanced_query, "Message Text", :for => :advanced_query, :class => "card-text mb-2" %>
        <div class="field form-group">
          <%= text_field_tag :advanced_query, params[:advanced_query], :class => "form-control col-md-12" %>
          <small id="advanced_queryHelp" class="form-text text-muted">Case insensitive search; to use regex, view the <%= link_to "regex documentation", help_regex_path %></small>
        </div>
      </div>
      <div class="col col-12 col-md-2">
        <%= label_tag :msg_id, "Message ID", :for => :msg_id, :class => "card-text mb-2" %>
        <div class="field form-group">
          <%= number_field_tag :msg_id, params[:msg_id], :min => "1", :max => ChatLogsHelper.chatlog_max_id, :class => "form-control col-md-12" %>
          <small id="msg_idHelp" class="form-text text-muted">A messages's ID, as a whole number</small>
        </div>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col col-12 col-md-2">
        <%= label_tag :channel, "Message Channel", :for => :channel, :class => "card-text mb-2" %>
        <div class="field form-group">
          <%= text_field_tag :channel, params[:channel], :class => "form-control col-md-12" %>
          <small id="channelHelp" class="form-text text-muted">Channel a reported message was sent in</small>
        </div>
      </div>
      <div class="col col-12 col-md-2">
        <%= label_tag :sender, "Message Sender", :for => :sender, :class => "card-text mb-2" %>
        <div class="field form-group">
          <%= text_field_tag :sender, params[:sender], :class => "form-control col-md-12" %>
          <small id="senderHelp" class="form-text text-muted">Sender of a reported message</small>
        </div>
      </div>
      <div class="col col-12 col-md-3">
        <%= label_tag :start_time, "Date Reported Start", :for => :start_time, :class => "card-text mb-2" %>
        <div class="field form-group">
          <div class="row">
            <div class="col">
              <div class="form-group">
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                  <%= text_field_tag :start_time, params[:start_time], :class => "form-control datetimepicker-input col-md-12", data: { target: "#datetimepicker1" }, :rows => "1" %>
                  <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker" title="Interactive date/time selector">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>
            </div>
            <script type="text/javascript">
            $(function () {
              $('#datetimepicker1').datetimepicker({
                format: '<%= "#{@prefs[:js_dt_format]}" %>'
                <%#= Documentation: https://tempusdominus.github.io/bootstrap-4/Options/#format %>
              });
            });
            </script>
          </div>
          <small id="start_timeHelp" class="form-text text-muted">Lower inclusive boundary.<br />Format: <%= @prefs[:user_dt_format] %></small>
        </div>
      </div>
      <div class="col col-12 col-md-3">
        <%= label_tag :end_time, "Date Reported End", :for => :end_time, :class => "card-text mb-2" %>
        <div class="field form-group">
          <div class="row">
            <div class="col">
              <div class="form-group">
                <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                  <%= text_field_tag :end_time, params[:end_time], :class => "form-control datetimepicker-input col-md-12", data: { target: "#datetimepicker2" }, :rows => "1" %>
                  <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker" title="Interactive date/time selector">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>
            </div>
            <script type="text/javascript">
            $(function () {
              $('#datetimepicker2').datetimepicker({
                format: '<%= "#{@prefs[:js_dt_format]}" %>'
                <%#= Documentation: https://tempusdominus.github.io/bootstrap-4/Options/#format %>
              });
            });
            </script>
          </div>
          <small id="end_timeHelp" class="form-text text-muted">Upper inclusive boundary.<br />Format: <%= @prefs[:user_dt_format] %></small>
          <noscript>
            <small id="end_timeHelp" class="form-text text-muted">You have JavaScript disabled, the date picker will not work without it.</small>
          </noscript>
        </div>
      </div>
      <div class="col col-md-2">
        <%= label_tag :per_page, "Results per Page", :for => :per_page, :class => "card-text mb-2" %>
        <div class="field form-group">
          <%= number_field_tag :per_page, params[:per_page], :min => PreferencesHelper.min_per_page, :max => PreferencesHelper.max_per_page, :class => "form-control col-md-12" %>
          <small id="per_pageHelp" class="form-text text-muted">Enter as a number from <%= PreferencesHelper.min_per_page %> to <%= PreferencesHelper.max_per_page %>. Default: <%= @prefs[:per_page] %></small>
        </div>
        <%= submit_tag 'Search', :class => "btn btn-primary col-auto float-right", :name => nil %>
      </div>
    </div>
  <% end %>
</div>

app/views/reports/edit.html.erb
<h2>Editing Message Copy</h2>

<div style="height: 1.0em;"><br></div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <p class="card-text">Original Message:</p>
        <table class="table table-responsive col-sm-5 p-0">
          <!-- No table header because I can't disable the bold text -->
          <tbody>
            <tr>
              <td>Channel</td>
              <td><%= @report.msg_channel %></td>
            </tr>
            <tr>
              <td>Sender</td>
              <td><%= @report.msg_sender %></td>
            </tr>
            <tr>
              <td>Message</td>
              <td><%= @report.msg_text %></td>
            </tr>
            <tr>
              <td>Date/Time</td>
              <td><%= ApplicationHelper.datetime_to_str(@report.msg_date, show_offset: true) %></td>
            </tr>
          </tbody>
        </table>
        <p class="card-text">This does not modify the original chat log entry, this should be done after resolving a report to remove sensitive or illegal content. If this is not the case, the copy of the message saved with the report should be left intact for administrative review purposes.</p>
        <%= render 'msg_edit_form', report: @report %>
      </div>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<h2>Report Message</h2>
<div style="height: 1.0em;"><br></div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <p class="card-text">Original Message:</p>
        <div class="table-responsive">
          <table class="table">
            <!-- No table header because I can't disable the bold text -->
            <tbody>
              <tr>
                <td class="col-sm-1">Channel</td>
                <%# Using "col-sm-1" applies it to the entire column, not just 1 cell %>
                <td><%= @chat_log.channel %></td>
              </tr>
              <tr>
                <td>Sender</td>
                <td><%= @chat_log.sender %></td>
              </tr>
              <tr>
                <td>Message</td>
                <td><%= @chat_log.message %></td>
              </tr>
              <tr>
                <td>Date/Time</td>
                <td><%= ApplicationHelper.datetime_to_str(ApplicationHelper.datetime_from_epoch(@chat_log.date), show_offset: true, show_seconds: true) %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <%= render 'form', report: @report %>
      </div>
    </div>
  </div>
</div>

app/views/reports/resolve.html.erb
<h2>Report Message</h2>
<div style="height: 1.0em;"><br></div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <p class="card-text">Original Message:</p>
        <table class="table table-responsive col-sm-5 p-0">
          <!-- No table header because I can't disable the bold text -->
          <tbody>
            <tr>
              <td>Channel</td>
              <td><%= @report.msg_channel %></td>
            </tr>
            <tr>
              <td>Sender</td>
              <td><%= @report.msg_sender %></td>
            </tr>
            <tr>
              <td>Message</td>
              <td><%= @report.msg_text %></td>
            </tr>
            <tr>
              <td>Date/Time</td>
              <td><%= ApplicationHelper.datetime_to_str(@report.msg_date, show_offset: true) %></td>
            </tr>
          </tbody>
        </table>
        <p class="card-text">Report Details:</p>
        <table class="table table-responsive col-sm-5 p-0">
          <!-- No table header because I can't disable the bold text -->
          <tbody>
            <tr>
              <td>Reporter</td>
              <%- if @report.user_id %>
                <td>Name: <%= User.find_by_id(@report.reporter).name %><br />
                    Email: <%= User.find_by_id(@report.reporter).email %><br />
                    User ID: <%= @report.reporter %> (<span title="Not yet implemented; will be added with admin console"><%= link_to "View Profile", root_path %></span>)
                </td>
              <% else %>
                <td>User ID: <%= @report.reporter %><br />
                    (User has deleted account)
                </td>
              <% end -%>
            </tr>
            <tr>
              <td>Reason</td>
              <td><%= @report.report_reason %></td>
            </tr>
            <tr>
              <td>Reported on</td>
              <td><%= ApplicationHelper.datetime_to_str(@report.created_at, show_offset: true) %></td>
            </tr>
            <tr>
              <td>Resolved?</td>
              <%- if @report.resolved? %>
                <td>Yes<br>
                    Action taken: <%= @report.resolving_action %></td>
              <% else %>
                <td>No</td>
              <% end -%>
            </tr>
            <%- if @report.resolved? %>
              <tr>
                <td>Resolved on</td>
                <td><%= ApplicationHelper.datetime_to_str(@report.resolved_at, show_offset: true) %></td>
              </tr>
              <tr>
                <td>Resolver</td>
                <%- if User.find_by_id(@report.resolver) %>
                  <td>Name: <%= User.find_by_id(@report.resolver).name %><br />
                      Email: <%= User.find_by_id(@report.resolver).email %><br />
                      User ID: <%= @report.resolver %> (<span title="Not yet implemented; will be added with admin console"><%= link_to "View Profile", root_path %></span>)
                  </td>
                <% else %>
                  <td>User ID: <%= @report.resolver %><br />
                      (User has deleted account)
                  </td>
                <% end -%>
              </tr>
            <% end -%>
          </tbody>
        </table>
        <%- if @chat_log %>
          <div class="actions">
            <p class="card-text">To modify or delete the message, click the button below (you will automatically be redirected back to this page to fill in the action taken field afterwards).</p>
            <p class="card-text">If you edit or delete the message, the table above will not change because it is a duplicate of the original message for administrative purposes.</p>
            <%= link_to 'Edit/Delete Message', edit_chat_log_path(@chat_log), :class => "btn btn-danger" %>
          </div>
          <br />
        <% else %>
          <p class="card-text">The message appears to have been deleted, no further edits can be made. (The table above has a duplicate of the original message kept for administrative purposes.)</p>
        <% end -%>

        <%= render 'resolve_form', report: @report %>
      </div>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<h2>Message Report</h2>
<div style="height: 1.0em;"><br></div>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <div class="row pt-3">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Original Message:</h4>
                <table class="table table-responsive ">
                  <!-- No table header because I can't disable the bold text -->
                  <tbody>
                    <tr>
                      <td>ID</td>
                      <td><%= @report.msg_id %></td>
                    </tr>
                    <tr>
                      <td>Channel</td>
                      <td><%= @report.msg_channel %></td>
                    </tr>
                    <tr>
                      <td>Sender</td>
                      <td><%= @report.msg_sender %></td>
                    </tr>
                    <tr>
                      <td>Message</td>
                      <td><%= @report.msg_text %></td>
                    </tr>
                    <tr>
                      <td>Date/Time</td>
                      <td><%= ApplicationHelper.datetime_to_str(@report.msg_date, show_offset: true) %></td>
                    </tr>
                  </tbody>
                </table>
                <%- if @MessageExists %>
                  <%= link_to "Message Context", chat_logs_path(:channel => @report.msg_channel, :base_id => @report.msg_id, :highlight => @report.msg_id) %><br />
                <% end -%>
                <%= link_to admin_reports_path(:msg_id => @report.msg_id, :resolved => :all, :highlight => @report.id), :class => "" do %>
                  View other reports for this message (<%= pluralize(@NumReportsForMessage, "report") %>)
                <% end %><br />
                <%= link_to admin_reports_path(:sender => @report.msg_sender, :resolved => :all, :highlight => @report.id), :class => "" do %>
                  View reports for messages from this sender (<%= pluralize(@NumReportsForSender, "report") %> across <%= pluralize(@NumMessagesReportedForSender, "message") %>)
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Report Information:</h4>
                <table class="table table-responsive ">
                  <!-- No table header because I can't disable the bold text -->
                  <tbody>
                    <tr>
                      <td>Reporter</td>
                      <%- if @report.user_id %>
                        <td>Name: <%= User.find_by_id(@report.reporter).name %><br />
                            Email: <%= User.find_by_id(@report.reporter).email %><br />
                            User ID: <%= @report.reporter %> (<%= link_to "View Profile", admin_manage_user_path(@report.reporter) %>)<br />
                            <%= link_to admin_reports_path(:user_id => @report.reporter, :resolved => :all, :highlight => @report.id), :class => "" do %>
                              View other reports from this user (<%= pluralize(@NumReportsFromReporter, "report") %>)
                            <% end %><br />
                        </td>
                      <% else %>
                        <td>User ID: <%= @report.reporter %><br />
                            (User has deleted account)
                        </td>
                      <% end -%>
                    </tr>
                    <tr>
                      <td>Reason</td>
                      <td><%= @report.report_reason %></td>
                    </tr>
                    <tr>
                      <td>Reported on</td>
                      <td><%= ApplicationHelper.datetime_to_str(@report.created_at, show_offset: true) %></td>
                    </tr>
                    <tr>
                      <td>Resolved?</td>
                      <%- if @report.resolved? %>
                        <td>Yes<br>
                            Action taken: <%= @report.resolving_action %></td>
                      <% else %>
                        <td>No</td>
                      <% end -%>
                    </tr>
                    <%- if @report.resolved? %>
                      <tr>
                        <td>Resolved on</td>
                        <td><%= ApplicationHelper.datetime_to_str(@report.resolved_at, show_offset: true) %></td>
                      </tr>
                      <tr>
                        <td>Resolver</td>
                        <%- if User.find_by_id(@report.resolver) %>
                          <td>Name: <%= User.find_by_id(@report.resolver).name %><br />
                              Email: <%= User.find_by_id(@report.resolver).email %><br />
                              User ID: <%= @report.resolver %> (<span title="Not yet implemented; will be added with admin console"><%= link_to "View Profile - in progress", root_path %></span>)<br />
                              <%= link_to "View other reports this user has resolved", admin_reports_path(:resolver_id => @report.resolver, :resolved => :resolved, :highlight => @report.id), :class => "" %>
                          </td>
                        <% else %>
                          <td>User ID: <%= @report.resolver %><br />
                              (User has deleted account)
                          </td>
                        <% end -%>
                      </tr>
                    <% end -%>
                  </tbody>
                </table>
                <%- if !@report.resolved? %>
                  <%= link_to 'Resolve Report', resolve_report_path(@report), :class => "btn btn-primary" %>
                <% end -%>
                <%= link_to 'Edit Message Copy', edit_report_path(@report), :class => "btn btn-warning" %>
                <%= link_to 'Delete Report', @report, method: :delete, data: { confirm: 'Are you sure you want to delete this report?' }, :class => "btn btn-danger", :role => "button" %>
                <br /><br />
                <%= link_to "View All Reports", admin_reports_path, :class => "" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>